services:
  model-service:
    image: ghcr.io/doda2025-team8/model-service:latest
    ports:
      - ${MODEL_PORT:-8081}:${MODEL_PORT:-8081}
    environment:
      - PORT=${MODEL_PORT:-8081}

  app-service:
    image: ghcr.io/doda2025-team8/app-service:latest
    ports:
      - ${APP_PORT:-8080}:${APP_PORT:-8080}
    environment:
      - PORT=${APP_PORT:-8080}
      - MODEL_SERVICE_URL=${MODEL_SERVICE_URL:http://model-service:8081}
    depends_on:
      - model-service
    
  app-frontend:
    image: ghcr.io/doda2025-team8/app-frontend:latest
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
    - app-service
