services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "${EXPOSED_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-service
      - app-frontend
  
  model-service:
    image: ghcr.io/doda2025-team8/model-service:${MODEL_SERVICE_VERSION}
    container_name: model-service
    environment:
      - MODEL_SERVICE_PORT=${MODEL_SERVICE_PORT}
      - MODEL_DIR=${MODEL_DIR}
      - MODEL_VERSION=${MODEL_VERSION}
      - GITHUB_REPO=${GITHUB_REPO}
    volumes:
      - ./output:${MODEL_DIR}

  app-service:
    image: ghcr.io/doda2025-team8/app-service:${APP_SERVICE_VERSION}
    container_name: app-service
    environment:
      - MODEL_HOST=${MODEL_HOST}
    depends_on:
      - model-service

  app-frontend:
    image: ghcr.io/doda2025-team8/app-frontend:${APP_FRONTEND_VERSION}
    container_name: app-frontend
