services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-service
      - app-frontend
    restart: unless-stopped
  
  model-service:
    image: ghcr.io/doda2025-team8/model-service:latest
    container_name: model-service
    ports:
      - "8081:8081"
    restart: unless-stopped

  app-service:
    image: app-service
    container_name: app-service
    environment:
      - MODEL_HOST=http://model-service:8081
    depends_on:
      - model-service
    restart: unless-stopped

  app-frontend:
    image: app-frontend
    container_name: app-frontend
    restart: unless-stopped
