apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: myprom-kube-prometheus-sta-alertmanager
  labels: 
    release: myprom
spec:
  replicas: 1
  alertmanagerConfigSelector:
    matchLabels:
      release: myprom