---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend-v1
  labels:
    app: app-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
      version: v1
  template:
    metadata:
      labels:
        app: app-frontend
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: app-frontend
          image: {{ .Values.frontend.image }}
          command: ["nginx", "-g", "daemon off;"]
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: frontend.conf
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-conf

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend-v2
  labels:
    app: app-frontend
    version: v2
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: app-frontend
      version: v2
  template:
    metadata:
      labels:
        app: app-frontend
        version: v2
        component: frontend
      annotations:
        sidecar.istio.io/inject: "true"
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: app-frontend
          image: {{ .Values.frontend.image }}
          command: ["nginx", "-g", "daemon off;"]
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: frontend.conf
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-conf

