{{- if not .Values.istio.enabled}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    app: sms-spam-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.rechability.grafanaHostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-grafana.default.svc.cluster.local
            port:
              number: 80
  - host: {{ .Values.rechability.prometheusHostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-kube-prometheus-prometheus.default.svc.cluster.local
            port:
              number: 9090
  - http:
      paths:
      - path: /sms
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 8080
      - path: /sms/metrics
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-frontend
            port:
              number: 8080
{{- end }}
