{{- if .Values.istio.enabled }}

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    {{- toYaml .Values.istio.ingressGatewaySelector | nindent 4 }}
  servers:
    - port:
        number: {{ .Values.istio.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.gateway.hosts }}
        - {{ . | quote }}
        {{- end }}

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-vs
spec:
  hosts:
    - "*"
  gateways:
    - my-gateway
  http:
    - match:
        - headers: 
            cookie:
              regex: "^(.*?;)?(canary-user=)(.*)?$"
      route:
        - destination:
            host: app-frontend
    - route:
      - destination:
          host: app-frontend
          subset: v1
        weight: 90
      - destination:
          host: app-frontend
          subset: v2
        weight: 10
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-frontend-dr
spec:
  host: app-frontend
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: "canary-user"
          ttl: 600s         
  subsets:
    - name: v1
      labels: { version: v1 }
    - name: v2
      labels: { version: v2 }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-service-dr
spec:
  host: app-service
  subsets:
    - name: v1
      labels: { version: v1 }
    - name: v2
      labels: { version: v2 }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: model-service-dr
spec:
  host: model-service
  subsets:
    - name: v1
      labels: { version: v1 }
    - name: v2
      labels: { version: v2 }
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: 
  name: app-service-vs
spec:
  hosts:
    - app-service
  http:
  - match:
    - sourceLabels:
        version: v2
    route:
    - destination:
        host: app-service
        subset: v2
  - route:
    - destination:
        host: app-service
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: 
  name: model-service-vs
spec:
  hosts:
    - model-service
  http:
  - match:
    - sourceLabels:
        version: v2
    route:
    - destination:
        host: model-service
        subset: v2
  - route:
    - destination:
        host: model-service
        subset: v1
{{- end }}
