{{- if .Values.istio.enabled }}

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    {{- toYaml .Values.istio.ingressGatewaySelector | nindent 4 }}
  servers:
    - port:
        number: {{ .Values.istio.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.gateway.hosts }}
        - {{ . | quote }}
        {{- end }}

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-vs
spec:
  hosts:
    - "*"
  gateways:
    - my-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: app-frontend
            subset: v1
          weight: 90
        - destination:
            host: app-frontend
            subset: v2
          weight: 10
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-frontend-dr
spec:
  host: app-frontend
  subsets:
    - name: v1
      labels: { version: v1 }
    - name: v2
      labels: { version: v2 }

{{- end }}
