{{- if .Values.istio.enabled}}

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    {{- toYaml .Values.istio.ingressGatewaySelector | nindent 4 }}
  servers:
    - port:
        number: {{ .Values.istio.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.gateway.hosts }}
        - {{ . | quote }}
        {{- end }}
        - {{ .Values.frontend.hostname | quote }}
        - {{ .Values.frontend.canaryHostname | quote }}
        - "grafana.team8.local"
        - "prometheus.team8.local"

{{- end }}
