apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
data:
  frontend.conf: |
    server {
        listen 8080;
        server_name localhost;

        location /sms {
            proxy_pass http://app-service:8080/sms;
            proxy_http_version 1.1;
            proxy_set_header Connection "";

            proxy_set_header Host app-service;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }